#!/bin/bash

if [ "$serverContext" == "lpdemo" ]; then

echo -e "\n\n===== Stopping LightningPipe Server ==================== \n";
forever stop $lightningPipeDir/server.js

fi


echo -e "\n\n===== Starting LightningPipe Server ==================== \n";

nodemon -w $lpProjectBase $lightningPipeDir/server.js

echo -e "\n\n========================================== \n";