#!/bin/bash


echo -e "\n\n===== Stopping LightningPipe Server (if any) ==================== \n";
forever stop $lightningPipeDir/server.js > /dev/null

echo -e "\n\n===== Starting LightningPipe Server ==================== \n";

nodemon -w $lpProjectBase $lightningPipeDir/server.js

echo -e "\n\n========================================== \n";